### PR TITLE
suggestion on halo cleanup

### PR DESCRIPTION
**Pull request by twicki**
## Technical Description

Changes the usage of halo values to be more consistent and puts less burden on the user.

#### Resolves / Enhances

Internal discussion we had

## Dependencies

This PR is independent

### CODE REVIEW

**Comment by twicki** [comment]
launch pipeline

**Comment by Stagno** [comment]
Once tests pass the PR is ready to be merged.

**Comment by twicki** [comment]
launch pipeline

**Comment by twicki** [comment]
launch jenkins

**Comment by twicki** [comment]
launch jenkins

**Comment by twicki** [comment]
launch pipeline

**Pull request merged**
