### PR TITLE
Fix clang format

### PR DESCRIPTION
**Pull request by cosunae**
# Technical Description 

Add a script that will format the whole repository and reformat broken format files

### CODE REVIEW

**Comment by thfabian** [comment]
There is a CMake function which provides a target that formats the entire project via `make format` (https://thfabian.github.io/dawn/cmake-modules/DawnAddTargetClangFormat.html)

**Comment by cosunae** [comment]
great, thanks, I didnt realize there was a target already, so I was running it by hand. 
I added the test directories to that target (except google test). 
However I think the fact that it works even if we dont have clang-format-3.8 is kind of problematic. In my system /usr/bin/clang-format is 3.7 and if I run it, it mess it up, since 3.7 and 3.8 will format in different way. 
Should we fix the version?

**Comment by thfabian** [comment]
You can force the `find_package` to only look for clang-format 3.8
```
find_package(clang-format 3.8)
```
and as usual directly pass `-DCLANG-FORMAT_EXECUTABLE=/path/to/clang-format` to CMake if it has trouble finding 3.8.

**Comment by cosunae** [comment]
yes, that make sense. I ll do that in a separate PR, since it requires first integrating that in dawn. 

Can we go ahead with this PR?

**Pull request merged**
