### PR TITLE
yodify

### PR DESCRIPTION
**Pull request by cosunae**

### CODE REVIEW

**Comment by cosunae** [comment]
launch jenkins

**Comment by cosunae** [comment]
launch jenkins

**Comment by twicki** [comment]
## Do not merge yet

We need to merge the [PR](https://github.com/MeteoSwiss-APN/dawn/pull/98) in dawn first and then change the git tag.

Good to see that jenkins is ok now, so we can do this asap

**Comment by cosunae** [comment]
launch jenkins

**Comment by cosunae** [comment]
launch jenkins

**Comment by cosunae** [comment]
launch jenkins

**Pull request merged**
