### PR TITLE
clang-6.0 support

### PR DESCRIPTION
**Pull request by stefanmoosbrugger**
Support for clang 6.0

Changes:
  * Compiler invocation is now taking a shared_ptr instead of a raw ptr.
  * ExprWithCleanups is now used in several cases. We can simply ignore the ExprWithCleanups as they are implicit and not in our interest.
  * CXXConstructorDecl->getNameAsString() returns the full name (e.g., struct foo instead of implicitly typedefed name foo) in some cases (e.g., CXXTemporaryObjectExpr). Retrieving the name from the RecordDecl fixes that. 

**Warning: The update is not fully backward compatible and thus not usable with clang-3.8. We have to try out if it works for clang 4 and 5.**

### CODE REVIEW

**Comment by stefanmoosbrugger** [comment]
launch jenkins

**Comment by stefanmoosbrugger** [comment]
launch jenkins

**Comment by stefanmoosbrugger** [comment]
launch jenkins

**Comment by stefanmoosbrugger** [comment]
launch jenkins

**Comment by twicki** [comment]
how are we planning on moving forward here?

**Comment by stefanmoosbrugger** [comment]
launch jenkins

**Comment by stefanmoosbrugger** [comment]
launch jenkins

**Comment by twicki** [comment]
launch jenkins

**Comment by twicki** [comment]
launch jenkins

**Comment by stefanmoosbrugger** [comment]
launch jenkins

**Pull request closed without merging**
