### PR TITLE
C++17 migration

### PR DESCRIPTION
**Pull request by Stagno**
Setting CMake to compile with c++17 standard.
Substituting additions to in STLExtras.h with the actual c++ 17 std:: versions

Depends on https://github.com/MeteoSwiss-APN/dawn/pull/276

### CODE REVIEW

**Comment by Stagno** [comment]
launch pipeline

**Comment by Stagno** [comment]
launch pipeline

**Comment by Stagno** [comment]
launch pipeline

**Comment by havogt** [comment]
launch pipeline

**Comment by havogt** [comment]
See #168.

**Pull request closed without merging**
