### PR TITLE
Update on dawn's AST refactoring (templating)

### PR DESCRIPTION
**Pull request by Stagno**
## Technical Description

Updates gtclang on dawn's AST refactoring.
Fixes tests.

## Dependencies

See PR on dawn: https://github.com/MeteoSwiss-APN/dawn/pull/259

### CODE REVIEW

**Comment by Stagno** [comment]
launch pipeline

**Comment by Stagno** [comment]
launch pipeline

**Comment by Stagno** [comment]
launch pipeline

**Comment by Stagno** [comment]
launch pipeline

**Comment by twicki** [comment]
refactoring takes another route

**Pull request closed without merging**
